# Generated by Django 4.2.7 on 2024-02-18 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intervention', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='report',
            name='mentor',
        ),
        migrations.RemoveField(
            model_name='report',
            name='student',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Mentor',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
