# Generated by Django 4.2.7 on 2024-02-19 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intervention', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
