# Generated by Django 5.0.2 on 2024-02-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervention', '0006_alter_appointment_appointmentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(),
        ),
    ]
