# Generated by Django 5.0.2 on 2024-02-22 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('intervention', '0008_delete_admin_remove_student_mentor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminId', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('adminName', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('mentorId', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('mentorName', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentId', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('studentName', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=128)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intervention.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('reportCategory', models.CharField(max_length=100)),
                ('reportText', models.TextField()),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intervention.mentor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intervention.student')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointmentDate', models.DateField()),
                ('venue', models.CharField(max_length=100)),
                ('time', models.TimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intervention.mentor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intervention.student')),
            ],
        ),
    ]
