# Generated by Django 5.0.2 on 2024-02-23 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervention', '0011_student_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, default='-', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, default='-', max_length=15, null=True),
        ),
    ]
