# Generated by Django 5.0.2 on 2024-02-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervention', '0012_alter_student_course_alter_student_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='Pending...', max_length=8),
        ),
    ]
