# Generated by Django 5.0.2 on 2024-02-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervention', '0013_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.TextField(blank=True, default='-', null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='purpose',
            field=models.TextField(blank=True, default='-', null=True),
        ),
    ]
