# Generated by Django 5.0.2 on 2024-02-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intervention', '0014_alter_appointment_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, default='Value not set', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, default='Value not set', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, default='Value not set', max_length=15, null=True),
        ),
    ]
