# Generated by Django 4.2.7 on 2024-01-09 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('authorID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('firstName', models.TextField(max_length=128)),
                ('lastName', models.TextField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Readers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField(max_length=128)),
                ('lastName', models.TextField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('bookID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('title', models.TextField(max_length=128)),
                ('genre', models.TextField(max_length=128)),
                ('pages', models.PositiveIntegerField()),
                ('authorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshelf.authors')),
            ],
        ),
    ]
