# Generated by Django 4.2.7 on 2024-01-09 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Readers',
        ),
    ]
