# Generated by Django 4.2.7 on 2024-01-09 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_delete_readers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Readers',
            fields=[
                ('readerID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('firstName', models.TextField(max_length=128)),
                ('lastName', models.TextField(blank=True, max_length=128)),
            ],
        ),
    ]
