# Generated by Django 4.2.7 on 2024-01-09 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_readers'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookStatus',
            field=models.CharField(default='Not Approved', max_length=128),
        ),
    ]
