# Generated by Django 4.2.7 on 2024-01-08 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albumName', models.CharField(max_length=128)),
                ('albumYear', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('singerID', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('singerName', models.CharField(max_length=128)),
                ('singerOrigin', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songID', models.CharField(max_length=6)),
                ('songName', models.CharField(max_length=128)),
                ('minutes', models.PositiveIntegerField()),
                ('albumName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songlist.album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='singerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songlist.singer'),
        ),
    ]
