# Generated by Django 4.2.7 on 2024-01-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='id',
        ),
        migrations.AlterField(
            model_name='song',
            name='songID',
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
