# Generated by Django 4.2.7 on 2024-01-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songlist', '0002_remove_song_id_alter_song_songid'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='songStatus',
            field=models.CharField(default='Hit', max_length=128),
        ),
    ]
