# Generated by Django 5.0.2 on 2024-02-21 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('lectId', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('lectName', models.CharField(max_length=200)),
                ('lectPass', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stuId', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('stuName', models.CharField(max_length=200)),
                ('stuPass', models.CharField(max_length=128)),
                ('stuMentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intervkpmb.lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('reportText', models.TextField()),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intervkpmb.lecturer')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intervkpmb.student')),
            ],
        ),
    ]
