# Generated by Django 5.0.2 on 2024-02-21 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intervkpmb', '0002_remove_student_stupass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='stuMentor',
            new_name='stuLec',
        ),
    ]
