# Generated by Django 4.2.7 on 2024-01-09 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actorID', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('actorName', models.TextField(max_length=200)),
                ('actorBirthDate', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('releaseDate', models.DateField(null=True)),
                ('genre', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ActorMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('castName', models.TextField(max_length=200)),
                ('actorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mykorea.actor')),
                ('movieID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mykorea.movie')),
            ],
        ),
    ]
