# Generated by Django 4.2.7 on 2024-01-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentorId', models.CharField(max_length=5)),
                ('mentorName', models.TextField(max_length=200)),
                ('roomNo', models.CharField(max_length=5)),
            ],
        ),
    ]
