# Generated by Django 4.2.7 on 2024-02-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('MentorID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('MentorName', models.TextField(max_length=100)),
                ('LectRoom', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('StudentName', models.TextField(max_length=100)),
                ('course', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TopManagement',
            fields=[
                ('staffNo', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('staffName', models.TextField(max_length=100)),
            ],
        ),
    ]
