# Generated by Django 4.2.7 on 2024-02-23 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ReleaseMate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('AppsID', models.AutoField(primary_key=True, serialize=False)),
                ('Program', models.TextField(max_length=1000)),
                ('Status', models.TextField(max_length=10)),
                ('ApplicationDate', models.DateField()),
                ('Mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReleaseMate.mentor')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ReleaseMate.student')),
            ],
        ),
    ]
